name: engine_dart
version: 0.0.1
description: Some preparatory work for GMTK.
author: todd beckman

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  built_collection: ^1.4.1
  browser: ^0.10.0
  logging: ^0.11.3
  meta: ^1.0.4
  react: ^3.1.1
  w_common: ^1.6.1

dev_dependencies:
  browser_detect: any
  dart_dev: ^1.7.7
  dart_style: ^0.2.11
  test: ^0.12.18

transformers:
  - $dart2js