name: engine_dart
version: 0.0.1
description: Some preparatory work for GMTK.
author: todd beckman
dependencies:
  browser: ^0.10.0
  logging: ^0.11.3
  over_react: ^1.1.1
  w_common: ^1.6.1
  w_flux: ^2.6.1
  w_module: ^1.2.5

dev_dependencies:
  browser_detect: any
  dart_dev: ^1.7.7
  dart_style: ^0.2.11
  test: ^0.12.18

transformers:
  - over_react
  - $dart2js